// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw_T8Avo27lNGDa213ek44bzSlm89VFfg',
    appId: '1:101782497272:web:ef6e3384ce99b3c3fed80d',
    messagingSenderId: '101782497272',
    projectId: 'sports-hub-2710',
    authDomain: 'sports-hub-2710.firebaseapp.com',
    databaseURL: 'https://sports-hub-2710-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sports-hub-2710.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwoFWFtXUuI_q8aMeFBJ56LzG863GGfe4',
    appId: '1:101782497272:android:ceb44143573a5738fed80d',
    messagingSenderId: '101782497272',
    projectId: 'sports-hub-2710',
    databaseURL: 'https://sports-hub-2710-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sports-hub-2710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9vjA1ezmIfmxpwUrIut3RXXgNFtMFjRU',
    appId: '1:101782497272:ios:0790793e74ffbe07fed80d',
    messagingSenderId: '101782497272',
    projectId: 'sports-hub-2710',
    databaseURL: 'https://sports-hub-2710-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sports-hub-2710.appspot.com',
    iosBundleId: 'com.example.sportHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9vjA1ezmIfmxpwUrIut3RXXgNFtMFjRU',
    appId: '1:101782497272:ios:2b37dd0e261cb021fed80d',
    messagingSenderId: '101782497272',
    projectId: 'sports-hub-2710',
    databaseURL: 'https://sports-hub-2710-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sports-hub-2710.appspot.com',
    iosBundleId: 'com.example.sportHubApp.RunnerTests',
  );
}
