// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNk_V2nNpdtt4GqidWyduMCHEEgrUagiA',
    appId: '1:101782497272:ios:d4194f84043eda5bfed80d',
    messagingSenderId: '101782497272',
    projectId: 'sports-hub-2710',
    databaseURL: 'https://sports-hub-2710-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sports-hub-2710.appspot.com',
    androidClientId: '101782497272-3dprg6mbvcpnl2319t7sl6ug8dfcahr5.apps.googleusercontent.com',
    iosClientId: '101782497272-q8cfcr6tfbqricnhs3f6ovdqmt8lseke.apps.googleusercontent.com',
    iosBundleId: 'com.example.SportsHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNk_V2nNpdtt4GqidWyduMCHEEgrUagiA',
    appId: '1:101782497272:ios:2e4f403eb5c4091cfed80d',
    messagingSenderId: '101782497272',
    projectId: 'sports-hub-2710',
    databaseURL: 'https://sports-hub-2710-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sports-hub-2710.appspot.com',
    androidClientId: '101782497272-3dprg6mbvcpnl2319t7sl6ug8dfcahr5.apps.googleusercontent.com',
    iosClientId: '101782497272-6rti13agi7etr2cdsobc288b3jj1pkpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportsHubIos',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw_T8Avo27lNGDa213ek44bzSlm89VFfg',
    appId: '1:101782497272:web:ef6e3384ce99b3c3fed80d',
    messagingSenderId: '101782497272',
    projectId: 'sports-hub-2710',
    authDomain: 'sports-hub-2710.firebaseapp.com',
    databaseURL: 'https://sports-hub-2710-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sports-hub-2710.appspot.com',
    measurementId: 'G-VF7VY1VNQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwoFWFtXUuI_q8aMeFBJ56LzG863GGfe4',
    appId: '1:101782497272:android:ceb44143573a5738fed80d',
    messagingSenderId: '101782497272',
    projectId: 'sports-hub-2710',
    databaseURL: 'https://sports-hub-2710-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sports-hub-2710.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYpvLqqLp1Z7etRo_4ET_6ffvt_EuvRdM',
    appId: '1:101782497272:web:6686075db7212de7fed80d',
    messagingSenderId: '101782497272',
    projectId: 'sports-hub-2710',
    authDomain: 'sports-hub-2710.firebaseapp.com',
    databaseURL: 'https://sports-hub-2710-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sports-hub-2710.appspot.com',
    measurementId: 'G-PRH9GTXKJY',
  );

}